#!/usr/bin/env python3
"""Install a project-local Cursor rule and the complete Tastemaker skill.

Usage: python3 skills/tastemaker/scripts/install_cursor.py /path/to/project
Re-running updates bundled files; project style locks and decisions are untouched.
"""
import argparse
import json
from pathlib import Path
import re
import shutil


MARKER = "<!-- Generated by tastemaker install_cursor.py. -->"


def make_rule(skill):
    match = re.match(r"\A---\r?\n(.*?)\r?\n---\r?\n", skill, re.S)
    if not match:
        raise ValueError("SKILL.md must have YAML frontmatter")
    description = next(
        (line.partition(":")[2].strip() for line in match[1].splitlines()
         if line.startswith("description:")),
        "Build, design, style, or improve a user interface with Tastemaker.",
    )
    body = skill[match.end():].lstrip()
    # Only rewrite bare skill paths. Preserve URLs and already qualified paths.
    body = re.sub(r"(?<![\w./:-])(references|scripts|assets|ideagram)/",
                  r".tastemaker/skill/\1/", body)
    return (
        "---\ndescription: " + json.dumps(description, ensure_ascii=False)
        + "\nalwaysApply: false\n---\n\n" + MARKER + "\n\n"
        + "Run commands from the project root. Supporting documents are copied "
        "unchanged: resolve their skill-relative paths against `.tastemaker/skill/` "
        "(and illustration sub-skill paths against `.tastemaker/skill/ideagram/`). "
        "Keep project memory in `.tastemaker/`, outside the installed skill.\n\n"
        + body
    )


def install(source, project):
    source, project = source.resolve(), project.resolve()
    destination = project / ".tastemaker" / "skill"
    rule = project / ".cursor" / "rules" / "tastemaker.mdc"
    if destination == source or source in destination.parents or destination in source.parents:
        raise ValueError("Source and installation directories must not overlap")
    for required in ("SKILL.md", "references", "scripts"):
        if not (source / required).exists():
            raise ValueError("Incomplete skill: missing " + required)
    rendered = make_rule((source / "SKILL.md").read_text(encoding="utf-8"))
    # Preflight every write, including parent symlinks, before copying any file.
    files = []
    for item in sorted(source.rglob("*")):
        relative = item.relative_to(source)
        if any(p in ("__pycache__", ".git") for p in relative.parts):
            continue
        if item.is_symlink():
            raise ValueError("Source symlinks are not supported: " + str(relative))
        if item.is_file() and item.suffix != ".pyc":
            files.append((item, destination / relative))
    manifest = destination / ".cursor-install.json"
    for target in [rule, manifest] + [target for _, target in files]:
        for path in [target] + list(target.parents):
            if path == project:
                break
            if path.is_symlink():
                raise ValueError("Refusing symlink destination: " + str(path))
    if rule.exists() and MARKER not in rule.read_text(encoding="utf-8"):
        raise ValueError("Existing tastemaker.mdc is not installer-managed")
    if destination.exists() and not manifest.is_file():
        raise ValueError("Existing skill directory is not installer-managed")
    if manifest.exists() and json.loads(manifest.read_text(encoding="utf-8")) != {
        "installer": "tastemaker-cursor", "version": 1
    }:
        raise ValueError("Unrecognized installer manifest")
    for item, target in files:
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)
    manifest.write_text(json.dumps({"installer": "tastemaker-cursor", "version": 1}) + "\n", encoding="utf-8")
    rule.parent.mkdir(parents=True, exist_ok=True)
    rule.write_text(rendered, encoding="utf-8", newline="\n")
    return rule


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path, help="Target Cursor project directory")
    args = parser.parse_args()
    try:
        rule = install(Path(__file__).resolve().parents[1], args.project)
    except (OSError, ValueError) as exc:
        parser.exit(1, str(exc) + "\n")
    print("Installed " + str(rule))


if __name__ == "__main__":
    main()
